# Default values for free5gc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

awsipmgmt:
  repository: public.ecr.aws/r8l3e1z0/aws-ip-manager
  tag: v0.1
  pullPolicy: IfNotPresent

dnn: "internet"

ueIPpool1: "10.63.0.0/16"
ueIPpool2: "10.64.0.0/16"

plmn:
  mcc: 208
  mnc: 93
  tac: '000001'

slicing:
  sst: 1
  sd: 112233

webui:
  image:
    repository: free5gc/webui
    pullPolicy: IfNotPresent
    tag: v4.0.0

mongodb:
  image:
    repository: mongo
    pullPolicy: IfNotPresent
    tag: "6.0.1"

k8swait:
  repository: groundnuty/k8s-wait-for #groundnuty/k8s-wait-for
  tag: v1.6
  pullPolicy: IfNotPresent  

ueransim:
   repository: registry.gitlab.com/infinitydon/registry/ueransim
   pullPolicy: IfNotPresent #Always
   tag: "v3.2.6" 

amf:
  image:
    repository: free5gc/amf
    pullPolicy: IfNotPresent
    tag: v4.0.0
  n2:
    multusIP: "10.100.50.11"
    multusNetworkMask: "24"

ausf:
  image:
    repository: free5gc/ausf
    pullPolicy: IfNotPresent
    tag: v4.0.0

udm:
  image:
    repository: free5gc/udm
    pullPolicy: IfNotPresent
    tag: v4.0.0
    
udr:
  image:
    repository: free5gc/udr
    pullPolicy: IfNotPresent
    tag: v4.0.0
    
nrf:
  image:
    repository: free5gc/nrf
    pullPolicy: IfNotPresent
    tag: v4.0.0

nssf:
  image:
    repository: free5gc/nssf
    pullPolicy: IfNotPresent
    tag: v4.0.0

pcf:
  image:
    repository: free5gc/pcf
    pullPolicy: IfNotPresent
    tag: v4.0.0
    
ue:
  imsi: "208930000000003"
  imei: "356938035643803"
  imeiSv: "4370816125816151"
  sst: "0x01"
  sd: "0x112233"
  op: "8e27b6af0e692e750f32667a3b14605d"
  secKey: "8baf473f2f8fd09487cccbd7097c6862"
  n1:
    multusIP: "10.100.50.16"
    multusNetworkMask: "24"

gnb:
  amfPort: "38412" 
  n2:
    multusIP: "10.100.50.15"
    multusNetworkMask: "24"
  n3:
    multusIP: "10.100.51.15"
    multusNetworkMask: "24"

smf:
  image:
    repository: free5gc/smf
    pullPolicy: IfNotPresent
    tag: v4.0.0
  n4:
    multusIP: "10.100.52.12"
    multusNetworkMask: "24" 

upf:
  image:
    repository: free5gc/upf
    pullPolicy: IfNotPresent
    tag: v4.0.0
  n3:
    multusIP: "10.100.51.13"
    multusNetworkMask: "24"
  n4:
    multusIP: "10.100.52.13"
    multusNetworkMask: "24"
  n6:
    multusIP: "10.100.100.13"
    multusNetworkMask: "24"  

multus:
  n2dev: "ens19"
  n3dev: "ens20"
  n4dev: "ens21"
  n6dev: "ens21"

# Subscriber information
subscribers:
  - imsi: "208930000000003"
    opcValue: "8e27b6af0e692e750f32667a3b14605d"
    plmnID: "20893"
    sequenceNumber: "16f3b3f70fc2"
    permanentKeyValue: "8baf473f2f8fd09487cccbd7097c6862"
    msisdn: "0900000001"
    sst: 1
    sd: "112233"
    uplink: "200 Mbps"
    downlink: "100 Mbps"
    dnn: "internet"
  - imsi: "208930000000004"
    opcValue: "8e27b6af0e692e750f32667a3b14605d"
    plmnID: "20893"
    sequenceNumber: "16f3b3f70fc2"
    permanentKeyValue: "8baf473f2f8fd09487cccbd7097c6862"
    msisdn: "0900000002"
    sst: 2
    sd: "010204"
    uplink: "300 Mbps"
    downlink: "150 Mbps"
    dnn: "internet"
  - imsi: "208930000000005"
    opcValue: "8e27b6af0e692e750f32667a3b14605d"
    plmnID: "20893"
    sequenceNumber: "16f3b3f70fc2"
    permanentKeyValue: "8baf473f2f8fd09487cccbd7097c6862"
    msisdn: "0900000003"
    sst: 1
    sd: "112233"
    uplink: "500 Mbps"
    downlink: "250 Mbps"
    dnn: "internet"