apiVersion: v1
kind: Service
metadata:
  name: nrf
  labels:
    epc-mode: nrf
spec:
  selector:
    epc-mode: nrf
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nrf-deployment
  labels:
    epc-mode: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nrf
  template:
    metadata:
      labels:
        epc-mode: nrf
    spec:  
      containers:
        - name: nrf
          image: "{{ .Values.nrf.image.repository }}:{{ .Values.nrf.image.tag }}"
          imagePullPolicy: {{ .Values.nrf.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
          - ./nrf -c config/nrfcfg.yaml;
          env:
            - name: GIN_MODE
              value: release 
          volumeMounts:
          - name: {{ .Release.Name }}-nrf-config
            mountPath: /free5gc/config/nrfcfg.yaml
            subPath: "nrfcfg.yaml"
          # Mount NRF TLS certificate secret
          - name: nrf-tls-certs
            mountPath: /etc/ssl/certs
            readOnly: true
          - name: nrf-tls-key
            mountPath: /etc/ssl/private
            readOnly: true
          # Root CA certificate and private key mounts (for OAuth2)
          - name: root-ca-complete
            mountPath: /etc/ssl/rootca/ca.crt
            subPath: ca.crt
            readOnly: true
          - name: root-ca-complete
            mountPath: /etc/ssl/rootca/ca.key
            subPath: ca.key
            readOnly: true
      volumes:
        - name: {{ .Release.Name }}-nrf-config
          configMap:
            name: {{ .Release.Name }}-nrf-config
        - name: nrf-tls-certs
          secret:
            secretName: nrf-tls-secret
            items:
            - key: tls.crt
              path: tls.crt
        - name: nrf-tls-key
          secret:
            secretName: nrf-tls-secret
            items:
            - key: tls.key
              path: tls.key
              mode: 0600
        - name: root-ca-complete
          secret:
            secretName: free5gc-root-ca-complete
            defaultMode: 0400