apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nssf
  labels:
    epc-mode: nssf
spec:
  selector:
    epc-mode: nssf  
  ports:
    - protocol: TCP
      port: 8000 
      targetPort: 8000  
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nssf-deployment 
  labels:
    epc-mode: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nssf
  template:
    metadata:    
      labels:
        epc-mode: nssf
    spec:  
      serviceAccountName: {{ .Release.Name }}-k8s-wait-for
      initContainers:
      - name: wait-for-nrf
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=nrf"               
      containers:
        - name: nssf
          image: "{{ .Values.nssf.image.repository }}:{{ .Values.nssf.image.tag }}"
          imagePullPolicy: {{ .Values.nssf.image.pullPolicy }}
          image: "{{ .Values.nssf.image.repository }}:{{ .Values.nssf.image.tag }}"
          imagePullPolicy: {{ .Values.nssf.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
          - ./nssf -c config/nssfcfg.yaml;
          env:
            - name: GIN_MODE
              value: release 
          volumeMounts:
          - name: {{ .Release.Name }}-nssf-config
            mountPath: /free5gc/config/nssfcfg.yaml
            subPath: "nssfcfg.yaml"
          - name: nssf-tls-certs
            mountPath: /etc/ssl/certs
            readOnly: true
          - name: nssf-tls-key
            mountPath: /etc/ssl/private
            readOnly: true
          - name: nrf-cert
            mountPath: /etc/ssl/nrf
            readOnly: true
      volumes:
        - name: {{ .Release.Name }}-nssf-config
          configMap:
            name: {{ .Release.Name }}-nssf-config       
        - name: nssf-tls-certs
          secret:
            secretName: nssf-tls-secret
            items:
            - key: tls.crt
              path: tls.crt
              mode: 0644
        - name: nssf-tls-key
          secret:
            secretName: nssf-tls-secret
            items:
            - key: tls.key
              path: tls.key
              mode: 0600
        - name: nrf-cert
          secret:
            secretName: nrf-tls-secret
            items:
            - key: tls.crt
              path: tls.crt
              mode: 0644    
