apiVersion: v1
kind: Service
metadata:
  name: udm
  labels:
    epc-mode: udm
spec:
  selector:
    epc-mode: udm
  ports:
    - protocol: TCP
      port: 8000   
      targetPort: 8000
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-udm-deployment
  labels:
    epc-mode: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: udm
  template:
    metadata:
      labels:
        epc-mode: udm
    spec: 
      serviceAccountName: {{ .Release.Name }}-k8s-wait-for
      initContainers:
      - name: wait-for-nrf
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=nrf"              
      containers:
        - name: udm
          image: "{{ .Values.udm.image.repository }}:{{ .Values.udm.image.tag }}"
          imagePullPolicy: {{ .Values.udm.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
          - ./udm -c config/udmcfg.yaml;
          env:
            - name: GIN_MODE
              value: release 
          volumeMounts:
          - name: {{ .Release.Name }}-udm-config
            mountPath: /free5gc/config/udmcfg.yaml
            subPath: "udmcfg.yaml"
          - name: udm-tls-certs
            mountPath: /etc/ssl/certs
            readOnly: true
          - name: udm-tls-key
            mountPath: /etc/ssl/private
            readOnly: true
          - name: nrf-cert
            mountPath: /etc/ssl/nrf
            readOnly: true
      volumes:
        - name: {{ .Release.Name }}-udm-config
          configMap:
            name: {{ .Release.Name }}-udm-config
        - name: udm-tls-certs
          secret:
            secretName: udm-tls-secret
            items:
            - key: tls.crt
              path: tls.crt
              mode: 0644
        - name: udm-tls-key
          secret:
            secretName: udm-tls-secret
            items:
            - key: tls.key
              path: tls.key
              mode: 0600
        - name: nrf-cert
          secret:
            secretName: nrf-tls-secret
            items:
            - key: tls.crt
              path: tls.crt
              mode: 0644 
