apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ueransim-config  
  labels:
    app: ueransim
data:
  free5gc-ue.yaml: |
    # IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 or 16 digits)
    supi: 'imsi-{{ .Values.ue.imsi }}'
    # Mobile Country Code value of HPLMN
    mcc: '{{ .Values.plmn.mcc }}'
    # Mobile Network Code value of HPLMN (2 or 3 digits)
    mnc: '{{ .Values.plmn.mnc }}'
    
    # Permanent subscription key
    key: '{{ .Values.ue.secKey }}'
    # Operator code (OP or OPC) of the UE
    op: '{{ .Values.ue.op }}'
    # This value specifies the OP type and it can be either 'OP' or 'OPC'
    opType: 'OPC'
    # Authentication Management Field (AMF) value
    amf: '8000'
    # IMEI number of the device. It is used if no SUPI is provided
    imei: '{{ .Values.ue.imei }}'
    # IMEISV number of the device. It is used if no SUPI and IMEI is provided
    imeiSv: '{{ .Values.ue.imeiSv }}'
    
    # List of gNB IP addresses for Radio Link Simulation
    gnbSearchList:
      - {{ .Values.gnb.n2.multusIP }}
    # UAC Access Identities Configuration
    uacAic:
      mps: false
      mcs: false

    # UAC Access Control Class
    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false      
    # Initial PDU sessions to be established
    sessions:
      - type: 'IPv4'
        apn: {{ .Values.dnn }}
        slice:
          sst: {{ .Values.ue.sst }}
          sd: {{ .Values.ue.sd }}
        emergency: false
    
    # Configured NSSAI for this UE by HPLMN
    configured-nssai:
      - sst: {{ .Values.ue.sst }}
        sd: {{ .Values.ue.sd }}
    
    # Default Configured NSSAI for this UE
    default-nssai:
      - sst: 1
        sd: 1
    
    # Supported encryption algorithms by this UE
    integrity:
      IA1: true
      IA2: true
      IA3: true
    
    # Supported integrity algorithms by this UE
    ciphering:
      EA1: true
      EA2: true
      EA3: true
    
    # Integrity protection maximum data rate for user plane
    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'
         
  free5gc-gnb.yaml: |
    mcc: '{{ .Values.plmn.mcc }}'          # Mobile Country Code value
    mnc: '{{ .Values.plmn.mnc }}'           # Mobile Network Code value (2 or 3 digits)
    
    nci: '0x000000010'  # NR Cell Identity (36-bit)
    idLength: 32        # NR gNB ID length in bits [22...32]
    tac: {{ .Values.plmn.tac }}             # Tracking Area Code
    
    linkIp: {{ .Values.gnb.n2.multusIP }}   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
    ngapIp: {{ .Values.gnb.n2.multusIP }}   # gNB's local IP address for N2 Interface (Usually same with local IP)
    gtpIp: {{ .Values.gnb.n3.multusIP }}   # gNB's local IP address for N3 Interface (Usually same with local IP)
    
    # List of AMF address information
    amfConfigs:
      - address: {{ .Values.amf.n2.multusIP }}
        port: {{ .Values.gnb.amfPort }}
    
    # List of supported S-NSSAIs by this gNB
    slices:
      - sst: {{ .Values.slicing.sst }}
        sd: {{ .Values.slicing.sd }}
    
    # Indicates whether or not SCTP stream number errors should be ignored.
    ignoreStreamIds: true