apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: openbao-csr-signer
spec:
  vault:
    server: http://openbao.openbao-system.svc.cluster.local:8200
    path: pki_int/sign/free5gc-csr
    auth:
      kubernetes:
        role: cert-manager
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: cert-manager