apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: openbao-root-ca
  namespace: cert-manager
spec:
  vault:
    server: http://openbao.openbao-system.svc.cluster.local:8200
    path: pki/root/sign-intermediate
    auth:
      kubernetes:
        role: cert-manager
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: cert-manager  # Uses existing cert-manager service account
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: openbao-intermediate-ca
  namespace: cert-manager
spec:
  vault:
    server: http://openbao.openbao-system.svc.cluster.local:8200
    path: pki_int/issue/free5gc-nf
    auth:
      kubernetes:
        role: cert-manager
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: cert-manager