# openbao-issuers-fixed.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: openbao-root-ca
spec:
  vault:
    server: http://openbao.openbao-system.svc.cluster.local:8200
    path: pki/root/sign-intermediate
    auth:
      kubernetes:
        role: cert-manager
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: cert-manager
        audiences:
          - https://kubernetes.default.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: openbao-intermediate-ca
spec:
  vault:
    server: http://openbao.openbao-system.svc.cluster.local:8200
    path: pki_int/issue/free5gc-nf
    auth:
      kubernetes:
        role: cert-manager
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: cert-manager
        audiences:
          - https://kubernetes.default.svc.cluster.local