apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: openbao-free5gc
spec:
  vault:
    server: http://openbao.openbao-system.svc.cluster.local:8200
    path: pki_int/sign/free5gc-services
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager
        serviceAccountRef:
          name: cert-manager