apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: free5gc-root-ca
  namespace: telco
spec:
  commonName: "root-ca.free5gc.local"
  isCA: true
  secretName: free5gc-root-ca-secret
  duration: 8760h
  renewBefore: 720h
  subject:
    organizationalUnits: ["free5GC Root CA"]
    organizations: ["free5GC Project"]
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - cert sign
    - crl sign
    - digital signature
    - key encipherment
  issuerRef:
    name: openbao-csr-signer
    kind: ClusterIssuer
    group: cert-manager.io